name: todo_list
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
